### ISSUE TITLE
Changing sampleNames after gating and transformation

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/openCyto#144]
Dear Mike and Finak, 
I started with very long sample names like below: 
### _GeneImpact NK batch 041317_GeneImpact gp100 RVXXXYYY Total Ig p50 mg mL **3333 M15**_006.fcs_
I would like to make the name short like: **3333_M15**
Can I know how to make the fcs names shorter after or before the transformation or gating steps?
Thank you.

**Comment by kdh4win4** [comment]
I just changed sample names before gating.

**Comment by mikejiang** [comment]
I thought we already addressed it in #143

**Comment by kdh4win4** [comment]
I changed the sample names but still have the original name on plotGate() result. 
Here is my code ;
```R
setwd("~/Total Ig/")
fcs_file_3 <- Sys.glob('*DLB01*.fcs') 
fs3 <- read.ncdfFlowSet(fcs_file_3)

new_names <- as.character(read.csv("gst_123_names_.csv")[,2])
sampleNames(fs3) <- new_names # it is same "character" class.
gs123 <- GatingSet(fs3) # 100 samples
gst_123 <- transform(gs123, trans_123) 
gating(gt_DLB01, gst_123)
```

**Comment by mikejiang** [comment]
Here is what you see in the `pData` 
```r
> pData(gs)
                                       name Center Sample Replicate
12828_1_Tcell_A01.fcs 12828_1_Tcell_A01.fcs  NHLBI  12828         1
12828_2_Tcell_A02.fcs 12828_2_Tcell_A02.fcs  NHLBI  12828         2
12828_3_Tcell_A03.fcs 12828_3_Tcell_A03.fcs  NHLBI  12828         3
...
```
`sampleNames` is the far left `rownames` of the `data.frame`, which is used as index or id.
The `name` column is the one used to be displayed in the plots.  The reason for both to be present is that the `sampleNames` (i.e. `rownames`) must be unique, but `name` column doesn't have to be.

So if you just want to change the name in the plot, simply do
```r
pData(gs)[["name"]] <- newNames
```
if you also want to change how you want to index the `gs`, then also use `sampleNames<-`
```

**Comment by kdh4win4** [comment]
I appreciate it. Mike. 
It works very well.
